version: '2'
services:
  mongo:
    image: "mongo:latest"
    ports:
    - "27017:27017"
    volumes:
    - ${PWD}/mongodata:/data/db
    container_name: "mongo"
  app:
    build: .
    depends_on:
    - "mongo"
    links:
    - "mongo"
    volumes:
    - ${PWD}/eosio-output:/output